- hosts: 127.0.0.1
  connection: local

  vars:
    ami: ami-c26bcab1 #eu-west-1 HMV 835.9.0 (stable)
    #ami: ami-c3cae3b4 #eu-west-1 HMV CoreOS 815.0.0 (alpha)
    env: "{{ environment_type }}"
    ipcode: P196
    systemCode: "CoreOS-Universal-Publishing"
    description: "CoreOS-Universal-Publishing"
    teamDL: "universal.publishing.platform@ft.com"
    environment_tag: default
    instanceType: m4.xlarge
  vars_files:
    - keys.yaml

  tasks:
    - ec2_vpc:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        state: present
        cidr_block: 172.24.0.0/16
        resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "CoreOS", "teamDL": "universal.publishing.platform@ft.com}"}
        subnets:
          - cidr: 172.24.0.0/18
            az: "{{ zones[0] }}"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "CoreOS subnet A", "teamDL": "universal.publishing.platform@ft.com}"}

          - cidr: 172.24.64.0/18
            az: "{{ zones[1] }}"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "CoreOS subnet B", "teamDL": "universal.publishing.platform@ft.com}"}

          - cidr: 172.24.128.0/18
            az: "{{ zones[2] }}"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "CoreOS subnet C", "teamDL": "universal.publishing.platform@ft.com}"}

          # AlertLogic/CloudInsight subnets. Not used by Coco cluster.
          - cidr: 172.24.192.0/28
            az:  "{{ region }}c"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "AlertLogic/CloudInsight subnet", "teamDL": "universal.publishing.platform@ft.com}"}
          - cidr: 172.24.192.16/28
            az:  "{{ region }}a"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "AlertLogic/CloudInsight subnet", "teamDL": "universal.publishing.platform@ft.com}"}
          - cidr: 172.24.192.32/28
            az:  "{{ region }}a"
            resource_tags: {"Name": "coreos", "env": "{{ env }}", "ipcode": "P196", "systemCode": "CoreOS", "description": "AlertLogic/CloudInsight subnet", "teamDL": "universal.publishing.platform@ft.com}"}

        internet_gateway: True
        route_tables:
          - subnets:
              - 172.24.0.0/18
              - 172.24.64.0/18
              - 172.24.128.0/18
              # AlertLogic/CloudInsight routing tables. Not used by Coco cluster. 
              - 172.24.192.0/28
              - 172.24.192.16/28
              - 172.24.192.32/28
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc

    - debug: msg="VPC {{ vpc }}"

    - name: Set up fleet security group
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{clusterid}}"
        description: Fleet security group
        vpc_id: "{{ vpc.vpc_id }}"
        rules:
          # OSB + LDNWebPerf
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 82.136.1.214/32
          # XP - Cluj office
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 194.117.242.0/23
          # Garton M - home
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 81.187.140.32/32
          # VPN client's outbound IP via tun0 interface
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 62.25.64.1/32
          # Allow 80 from everywhere
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # Allow 443 from everywhere
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          # Allow internal requests
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 172.24.0.0/16
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
          # Allow timesync/ntp out
          - proto: udp
            from_port: 123
            to_port: 123
            cidr_ip: 0.0.0.0/0
      register: fleet_group

    - name: Tag UP CoreOS security group
      ec2_tag:
        resource: "{{fleet_group.group_id}}"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        state: present
        tags:
          Name: "coreos-up-{{clusterid}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          coco-environment-tag: "{{environment_tag}}"

    - name: cluster-elb
      ec2_elb_lb:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{clusterid}}"
        state: present
        security_group_ids: '{{fleet_group.group_id}}'
        subnets:
          - "{{ vpc.subnets[0].id }}"
          - "{{ vpc.subnets[1].id }}"
          - "{{ vpc.subnets[2].id }}"
        listeners:
          - protocol: https
            load_balancer_port: 443
            instance_protocol: http
            instance_port: 80
            ssl_certificate_id: "arn:aws:iam::027104099916:server-certificate/wildcard.ft.com"
        purge_listeners: True
        health_check:
          ping_protocol: tcp # options are http, https, ssl, tcp
          ping_port: 80
          #ping_path: "/index.html" # not required for tcp or ssl
          response_timeout: 5 # seconds
          interval: 30 # seconds
          unhealthy_threshold: 2
          healthy_threshold: 10
      register: cluster_elb

    - name: tag ELB
      shell: ". /.venv/bin/activate && aws --region {{region}} elb add-tags --load-balancer-names coreos-up-{{clusterid}} --tags Key=Name,Value=coreos-up-{{clusterid}} Key=env,Value={{env}} Key=ipcode,Value={{ipcode}} Key=systemCode,Value={{systemCode}} Key=description,Value={{description}} Key=teamDL,Value={{teamDL}} Key=coco-environment-tag,Value={{environment_tag}}"

    - debug: msg="cluster_elb dns {{ cluster_elb.elb.dns_name }}"

    - name: Provision m3.large instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{clusterid}}"
        image: "{{ami}}"
        instance_type: "{{instanceType}}"
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/default_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[1].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 100
            volume_type: gp2
            delete_on_termination: true
        count_tag:
          Name: "ftstt{{clusterid}}-caw1b-eu-p"
        instance_tags:
          Name: "ftstt{{clusterid}}-caw1b-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"

    - name: Provision m3.large instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{clusterid}}"
        image: "{{ami}}"
        instance_type: "{{instanceType}}"
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/default_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[2].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 100
            volume_type: gp2
            delete_on_termination: true
        count_tag:
          Name: "ftstt{{clusterid}}-caw1c-eu-p"
        instance_tags:
          Name: "ftstt{{clusterid}}-caw1c-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"

    - set_fact:
        persistent_tag: 1

    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{clusterid}}"
        image: "{{ami}}"
        instance_type: "{{instanceType}}" 
        wait: true
        exact_count: 1
        ebs_optimized: true
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 100
            volume_type: gp2
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            volume_type: gp2
            delete_on_termination: true
        count_tag:
          Name: "ftpr1{{clusterid}}-caw1a-eu-p"
        instance_tags:
          Name: "ftpr1{{clusterid}}-caw1a-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"

    - set_fact:
        persistent_tag: 2
      
    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{clusterid}}"
        image: "{{ami}}"
        instance_type: "{{instanceType}}" 
        wait: true
        exact_count: 1
        ebs_optimized: true
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[1].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 100
            volume_type: gp2
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            volume_type: gp2
            delete_on_termination: true
        count_tag:
          Name: "ftpr2{{clusterid}}-caw1b-eu-p"
        instance_tags:
          Name: "ftpr2{{clusterid}}-caw1b-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"

    - set_fact:
        persistent_tag: 3
      
    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{clusterid}}"
        image: "{{ami}}"
        instance_type: "{{instanceType}}"
        wait: true
        exact_count: 1
        ebs_optimized: true
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[2].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 100
            volume_type: gp2
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            volume_type: gp2
            delete_on_termination: true
        count_tag:
          Name: "ftpr3{{clusterid}}-caw1c-eu-p"
        instance_tags:
          Name: "ftpr3{{clusterid}}-caw1c-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"

    - name: Cluster tunnel DNS address
      debug: msg="Cluster tunnel DNS address: {{ environment_tag }}-tunnel-up.ft.com"

